# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: docker

steps:
- script: docker pull katalonstudio/katalon:8.3.0.beta
  displayName: 'Pull katalon studio images'
- script: cd ..
- script: dir
- script: cd ..
- script: dir
- script: docker run -t --rm -v "%cd%":/tmp/project katalonstudio/katalon katalonc.sh -projectPath=/tmp/project -testSuitePath="Test Suites/web-service-tests - All Test Cases" -browserType="Web Service" -executionProfile="default" -apiKey="4e2f841d-2558-4b6d-933c-14f0192acd8b"
  displayName: 'Runnning Katalon TS_RegressionTest'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/